begin
  require 'ant'
rescue LoadError
  puts 'This Rakefile requires JRuby. Please use jruby -S rake.'
  exit 1
end

require 'dubious_tasks'

require 'rake/clean'

OUTDIR = 'WEB-INF/classes'

def class_files_for files
  files.map do |f|
    explode = f.split('/')[1..-1]
    explode.last.gsub!(/(^[a-z]|_[a-z])/) {|m|m.sub('_','').upcase}
    explode.last.sub! /\.(duby|java|mirah)$/, '.class'
    OUTDIR + '/' + explode.join('/')
  end
end

Duby.dest_paths << OUTDIR
Duby.source_paths << '.'
Duby.compiler_options << '--classpath' << [File.expand_path(OUTDIR), *FileList["WEB-INF/lib/*.jar"].map{|f|File.expand_path(f)}].join(':') + ':' + CLASSPATH

CLEAN.include(OUTDIR)
CLOBBER.include("WEB-INF/lib/dubious.jar", 'WEB-INF/appengine-generated')

APP_SRC = [File.expand_path "app.mirah"]
APP_CLASSES = ["#{OUTDIR}/ShoutController.class","#{OUTDIR}/Shout.class"]
TEMPLATES = Dir["views/**/*.erb"]

directory OUTDIR

APP_CLASSES.each do |klass|
  file klass => APP_SRC do
    mirahc *APP_SRC
  end
end

file MODEL_JAR => MODEL_SRC_JAR do |t|
  cp MODEL_SRC_JAR, MODEL_JAR
end

appengine_app :app, 'app', '' => APP_CLASSES

namespace :compile do
  task :app => APP_CLASSES
end

desc "compile app"
task :compile => 'compile:app'

task :default => :server

